### PR TITLE
Fixed GO crashing due to race condition when closing an organ

### LINKED ISSUE #1678: Crash when closing an organ
Every now and then closing an organ causes a crash or strange behavior. The strange behaviour could be something like creating a cache while caching is off or pressing a key when a stop is pulled. The crash occurs more often if the organ uses a lot of memory, but it can also occur with smaller organs. Steps to reproduce:

Load or open an organ
Close
Repeat

GO version: 3.13.0

[Crash Reports.zip](https://github.com/GrandOrgue/grandorgue/files/12873434/Crash.Reports.zip)

### PR DESCRIPTION
**Pull request by nanoufo**
Fixes #1678.
GOSoundThreads could run work items that were deleted concurrently. 
This PR ensures that GOSoundThreads don't hold any work items when GOSound::AssignOrganFile() is deleting them.

### CODE REVIEW

File: src/grandorgue/sound/scheduler/GOSoundThread.cpp [hunk 1]
```diff
@@ -35,15 +40,26 @@ void GOSoundThread::Entry() {
       break;
 
     GOMutexLocker lock(m_Mutex, false, "GOSoundThread::Entry", this);
-
+    m_IsIdle = true;
+    m_IdleStateReachedCondition.Broadcast();
     if (!lock.IsLocked() || ShouldStop())
       break;
```
Comment (oleg68) [inline src/grandorgue/sound/scheduler/GOSoundThread.cpp:46]:
```suggestion
    if (!lock.IsLocked() || ShouldStop())
      break;
    m_IsIdle = true;
    m_IdleStateReachedCondition.Broadcast();
```

File: src/grandorgue/sound/scheduler/GOSoundThread.h [hunk 2]
```diff
@@ -20,12 +20,25 @@ class GOSoundThread : public GOThread {
 
   GOMutex m_Mutex;
   GOCondition m_Condition;
+  GOCondition m_IdleStateReachedCondition;
+  bool m_IsIdle; // guarded by m_Mutex
```
Comment (oleg68) [inline src/grandorgue/sound/scheduler/GOSoundThread.h:24]:
```suggestion
  // whether the thread sleeps and waits for waking up with m_Condition
  bool m_IsIdle; // guarded by m_Mutex
```

File: src/grandorgue/sound/GOSound.cpp [hunk 3]
```diff
@@ -54,6 +54,11 @@ void GOSound::StartThreads() {
     m_Threads[i]->Run();
 }
 
+void GOSound::WaitForThreadsToReleaseWorkItems() {
+  for (unsigned i = 0; i < m_Threads.size(); i++)
+    m_Threads[i]->WaitForReleaseOfWorkItems();
```
Comment (oleg68) [inline src/grandorgue/sound/GOSound.cpp:59]:
```suggestion
  for (pThread : m_Threads)
    pThread->WaitForReleaseOfWorkItems();
```

File: src/grandorgue/sound/GOSound.cpp [hunk 4]
```diff
@@ -54,6 +54,11 @@ void GOSound::StartThreads() {
     m_Threads[i]->Run();
 }
 
+void GOSound::WaitForThreadsToReleaseWorkItems() {
```
Comment (oleg68) [inline src/grandorgue/sound/GOSound.cpp:57]: This function is used only once, so it is not needed.

File: src/grandorgue/sound/scheduler/GOSoundScheduler.cpp [hunk 5]
```diff
@@ -127,6 +131,9 @@ void GOSoundScheduler::Exec() {
 
 GOSoundWorkItem *GOSoundScheduler::GetNextGroup() {
   do {
+    if (m_IsNotGivingWork) {
```
Comment (oleg68) [inline src/grandorgue/sound/scheduler/GOSoundScheduler.cpp:134]:
```suggestion
    if (m_IsNotGivingWork.load()) {
```

File: src/grandorgue/sound/scheduler/GOSoundScheduler.h [hunk 6]
```diff
@@ -46,6 +48,9 @@ class GOSoundScheduler {
   void Add(GOSoundWorkItem *item);
   void Remove(GOSoundWorkItem *item);
 
+  void PauseGivingWork() { m_IsNotGivingWork = true; }
+  void ResumeGivingWork() { m_IsNotGivingWork = false; }
```
Comment (oleg68) [inline src/grandorgue/sound/scheduler/GOSoundScheduler.h:52]:
```suggestion
  void PauseGivingWork() { m_IsNotGivingWork.store(true); }
  void ResumeGivingWork() { m_IsNotGivingWork.store(false); }
```

File: src/grandorgue/sound/scheduler/GOSoundThread.h [hunk 7]
```diff
@@ -20,12 +20,26 @@ class GOSoundThread : public GOThread {
...
+   * === Prerequisites ===
+   * During the execution the following must be true:
+   * 1. m_Scheduler->GetNextGroup() always returns nullptr
+   * 2. thread is running and is not marked to be stopped
+   *
+   * === Result ===
+   * Method returns when the thread forgets all pointers to work items
+   * (so that work items can be deleted safely)
+   */
+  void WaitForReleaseOfWorkItems();
```
Comment (oleg68) [inline src/grandorgue/sound/scheduler/GOSoundThread.h:42]:
```suggestion
  void WaitForIdle();
```

**Comment by oleg68** [comment]
@nanoufo 

Please add an entry to CHANGELOG.md:
```
- Fixed crash on closing an organ https://github.com/GrandOrgue/grandorgue/issues/1678
```

**Comment by oleg68** [comment]
@willeke1234 could you test tne new fix?

**Review by oleg68 — APPROVED** [review]

**Comment by willeke1234** [comment]
@oleg68 This fix looks ok. GO reloaded 30+ times without crashing.

**Comment by oleg68** [comment]
> @oleg68 This fix looks ok. GO reloaded 30+ times without crashing.

This fix has been changed after your first test. Have you tested the last version?

**Comment by willeke1234** [comment]
@oleg I think so. I downloaded the source code from https://github.com/nanoufo/grandorgue after you asked me to test. If this isn't the last version then where and when can I find the version to test?

**Comment by oleg68** [comment]
Yes, it is the last version.

**Review by larspalo — APPROVED** [review]

**Comment by rousseldenis** [comment]
Very nice! @nanoufo thanks for this. Closing GO has never been so smooth!
